apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-exporter
subjects:
- kind: ServiceAccount
  name: local-path-provisioner-exporter
  namespace: observability
roleRef:
  kind: ClusterRole
  name: local-path-provisioner-exporter
  apiGroup: rbac.authorization.k8s.io
