apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-path-provisioner-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: local-path-provisioner-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-path-provisioner-exporter
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: app
        image: echern/local-path-provisioner-exporter:0.1.0
        env:
        - name: DEFAULT_PATH
          value: /data/local-path-provisioner
        - name: DELAY_SECONDS
          value: '30'
        - name: STORAGE_CLASS
          value: local-path
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: data
          mountPath: /data/local-path-provisioner
        ports:
        - name: http
          containerPort: 2112
        securityContext:
          runAsUser: 0
      terminationGracePeriodSeconds: 30
      serviceAccountName: local-path-provisioner-exporter
      volumes:
      - name: data
        hostPath:
          path: /data/local-path-provisioner
