apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: observability

resources:
- daemonset.yaml
- service.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- servicemonitor.yaml
