apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: local-path-provisioner-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: local-path-provisioner-exporter
  endpoints:
  - port: http
    path: /metrics
    interval: 60s
