apiVersion: v1
kind: Service
metadata:
  name: local-path-provisioner-exporter
  labels:
    app.kubernetes.io/name: local-path-provisioner-exporter
spec:
  selector:
    app.kubernetes.io/name: local-path-provisioner-exporter
  ports:
    - protocol: TCP
      port: 2112
      targetPort: http
      name: http
